### ISSUE TITLE
Failed to connect to the MQ-host Network Error : %!s(<nil>)

### ISSUE THREAD

**Issue by JannikZed** [skx/tunneller#13]
I'm using a little self-hosted instance and things worked fine for a long time. Right now, I can't connect to the server any more, as I receive the error `Failed to connect to the MQ-host Network Error : %!s(<nil>)`..
I restarted the server already, without any success..
Any idea on how to debug this problem?

**Comment by skx** [comment]
1.  Login to the server and confirm mosquitto is running, and listening on a public IP.
2.  If it isn't check the logs.
3.  If it is try telneting from your home/similar to rule out firewall.

Those would be the three basic things I'd check.

**Comment by JannikZed** [comment]
everything was running fine on the server - after a client restart, it started working again! Strange thing .. I could successfully connect to the MQT server via telnet.
